export const languages = [
  { value: "English(USA)", label: "English(USA)" },
  { value: "English(UK)", label: "English(UK)" },
  { value: "Mandarin Chinese", label: "Mandarin Chinese" },
  { value: "Hindi", label: "Hindi" },
  { value: "Spanish", label: "Spanish" },
  { value: "French", label: "French" },
  { value: "Modern Standard Arabic", label: "Modern Standard Arabic" },
  { value: "Bengali", label: "Bengali" },
  { value: "Russian", label: "Russian" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Urdu", label: "Urdu" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "German", label: "German" },
  { value: "Japanese", label: "Japanese" },
  { value: "Nigerian Pidgin", label: "Nigerian Pidgin" },
  { value: "Marathi", label: "Marathi" },
  { value: "Telugu", label: "Telugu" },
  { value: "Turkish", label: "Turkish" },
  { value: "Tamil", label: "Tamil" },
  { value: "Yue Chinese", label: "Yue Chinese" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Tagalog", label: "Tagalog" },
  { value: "Wu Chinese", label: "Wu Chinese" },
  { value: "Korean", label: "Korean" },
  { value: "Iranian Persian (Farsi)", label: "Iranian Persian (Farsi)" },
  { value: "Hausa", label: "Hausa" },
  { value: "Egyptian Spoken Arabic", label: "Egyptian Spoken Arabic" },
  { value: "Swahili", label: "Swahili" },
  { value: "Javanese", label: "Javanese" },
  { value: "Italian", label: "Italian" },
  { value: "Western Punjabi", label: "Western Punjabi" },
  { value: "Kannada", label: "Kannada" },
  { value: "Gujarati", label: "Gujarati" },
  { value: "Thai", label: "Thai" },
];
