export const dummyEditorData = [
  "/main/editor/bold.png",
  "/main/editor/italic.png",
  "/main/editor/underline.png",
  "/main/editor/align-left.png",
  "/main/editor/align-center.png",
  "/main/editor/align-right.png",
  "/main/editor/align-stretch.png",
  "/main/editor/bullets-decimal.png",
  "/main/editor/bullets-dot.png",
  "/main/editor/text-style.png",
  "/main/editor/text-arrow.png",
  "/main/editor/text-height.png",
  "/main/editor/background-fill.png",
  "/main/editor/style-link.png",
]