export const VOICE_OPTIONS = {
  english: [
     { value: "Joanna", label: "Joanna (Female)", accent: "US" },
    { value: "Kendra", label: "Kendra (Female)", accent: "US" },
    { value: "Kimberly", label: "Kimberly (Female)", accent: "US" },
    { value: "Salli", label: "Salli (Female)", accent: "US" },
    { value: "Joey", label: "Joey (Male)", accent: "US" },
    { value: "Justin", label: "Justin (Male Child)", accent: "US" },
    { value: "Matthew", label: "Matthew (Male)", accent: "US" },
     { value: "Amy", label: "Amy (Female)", accent: "British" },
    { value: "Emma", label: "Emma (Female)", accent: "British" },
    { value: "Brian", label: "Brian (Male)", accent: "British" },
     { value: "Aditi", label: "Aditi (Female)", accent: "Indian" },
    { value: "Raveena", label: "Raveena (Female)", accent: "Indian" },
    { value: "Zeina", label: "Zeina (Female)", accent: "Modern" },
    { value: "Hala", label: "Hala (Female)", accent: "Gulf" },
    { value: "Zayd", label: "Zayd (Male)", accent: "Gulf" },
    { value: "Hiujin", label: "Hiujin (Female)", accent: "Cantonese" },
    { value: "Zhiyu", label: "Zhiyu (Female)", accent: "Mandarin" },
     { value: "Mizuki", label: "Mizuki (Female)", accent: "Japanese" },
    { value: "Takumi", label: "Takumi (Male)", accent: "Japanese" },
     { value: "Seoyeon", label: "Seoyeon (Female)", accent: "Korean" },
    { value: "Conchita", label: "Conchita (Female)", accent: "Spanish" },
    { value: "Lucia", label: "Lucia (Female)", accent: "Spanish" },
    { value: "Enrique", label: "Enrique (Male)", accent: "Spanish" },
     { value: "Celine", label: "Celine (Female)", accent: "French" },
    { value: "Lea", label: "Lea (Female)", accent: "French" },
    { value: "Mathieu", label: "Mathieu (Male)", accent: "French" },
     { value: "Marlene", label: "Marlene (Female)", accent: "German" },
    { value: "Vicki", label: "Vicki (Female)", accent: "German" },
    { value: "Hans", label: "Hans (Male)", accent: "German" },
     { value: "Carla", label: "Carla (Female)", accent: "Italian" },
    { value: "Bianca", label: "Bianca (Female)", accent: "Italian" },
    { value: "Giorgio", label: "Giorgio (Male)", accent: "Italian" },
    { value: "Naja", label: "Naja (Female)", accent: "Danish" },
    { value: "Mads", label: "Mads (Male)", accent: "Danish" },
     { value: "Ewa", label: "Ewa (Female)", accent: "Polish" },
    { value: "Maja", label: "Maja (Female)", accent: "Polish" },
    { value: "Jan", label: "Jan (Male)", accent: "Polish" },
     { value: "Camila", label: "Camila (Female)", accent: "Brazilian" },
    { value: "Vitoria", label: "Vitoria (Female)", accent: "Brazilian" },
  ],
};

export const LANGUAGE_OPTIONS = [
  { value: "en-US", label: "English (US)", voices: "english" },
  { value: "en-GB", label: "English (UK)", voices: "english" },
  { value: "en-IN", label: "English (India)", voices: "english" },
  { value: "arb", label: "Arabic (Modern)", voices: "arabic" },
  { value: "ar-AE", label: "Arabic (Gulf)", voices: "arabic" },
  { value: "cmn-CN", label: "Chinese (Mandarin)", voices: "asian" },
  { value: "yue-CN", label: "Chinese (Cantonese)", voices: "asian" },
  { value: "ja-JP", label: "Japanese", voices: "asian" },
  { value: "ko-KR", label: "Korean", voices: "asian" },
  { value: "es-ES", label: "Spanish", voices: "european" },
  { value: "fr-FR", label: "French", voices: "european" },
  { value: "de-DE", label: "German", voices: "european" },
  { value: "it-IT", label: "Italian", voices: "european" },
];

export const AUDIO_FORMATS = [
  { value: "mp3", label: "MP3", quality: "High Compression" },
  { value: "pcm", label: "PCM", quality: "Lossless" },
  { value: "ogg_vorbis", label: "OGG Vorbis", quality: "Medium Quality" },
] as const;

export const SPEAKING_STYLES = [
  { value: "neutral", label: "Neutral" },
  { value: "newscaster", label: "Newscaster" },
  { value: "conversational", label: "Conversational" },
];
