import React from "react";

export default function AiSearch() {
	return (
		<section className="space-y-6">
			<div className="space-y-4">
				<h1 className="font-bold text-lg">AI Search Engine</h1>
				<p className="text-white/70 text-sm leading-relaxed">
					Welcome to WhopMe.com's AI Search Engine, your intelligent tool for
					exploring the web. Here's how to get started:
				</p>
			</div>
			<div className="space-y-4">
				<h1 className="font-bold text-lg">Step 2: Enter Your Query</h1>
				<p className="text-white/70 text-sm leading-relaxed">
					In the search bar, type in your query. This could be a question, a
					keyword, or a phrase you want to learn more about. Our AI Search
					Engine is designed to understand natural language, so feel free to ask
					as if you're speaking to a human.
				</p>
			</div>
			<div className="space-y-4">
				<h1 className="font-bold text-lg">Step 3: Analyze the Results</h1>
				<p className="text-white/70 text-sm leading-relaxed">
					Press enter or click on the search icon. In a matter of seconds, our
					AI Search Engine will present you with a list of the most relevant
					results. These results are generated by our advanced AI algorithm that
					understands the context of your query and filters through billions of
					web pages to find the most accurate and helpful information.
				</p>
			</div>
			<div className="space-y-4">
				<h1 className="font-bold text-lg">Step 4: Refine Your Search</h1>
				<p className="text-white/70 text-sm leading-relaxed">
					If you're not satisfied with the initial results, you can refine your
					search. Use quotations for exact phrases, the word 'AND' to combine
					searches, or 'OR' to expand your search. Our AI Search Engine
					understands these commands and will adjust the results accordingly.
				</p>
			</div>
			<div className="space-y-4">
				<h1 className="font-bold text-lg">Step 5: Explore Further</h1>
				<p className="text-white/70 text-sm leading-relaxed">
					Welcome to WhopMe.com's AI Search Engine, your intelligent tool for
					exploring the web. Here's how to get started:
				</p>
				<p className="text-white/70 text-sm leading-relaxed">
					Click on any of the search results to explore further. Our AI Search
					Engine aims to provide a comprehensive understanding of your query by
					sourcing information from a variety of reliable and authoritative
					sites.
				</p>
				<p className="text-white/70 text-sm leading-relaxed">
					Remember, our AI Search Engine is a tool designed to make your online
					exploration easier, faster, and more accurate. If you have any
					questions or need further assistance, please don't hesitate to reach
					out to our support team.
				</p>
				<p className="text-white/70 text-sm leading-relaxed">
					Stay tuned as we guide you through our other innovative AI tools!
				</p>
			</div>
		</section>
	);
}
