export const cardData = [
  {
    icon : '/svgs/Vector5.svg',
    title : "Sales",
    description : "We are just a call away! Get in touch with our sales team.",
  },
  {
    icon : '/svgs/Vector9.svg',
    title : "Chat",
    description : "Need help? Our support team is available to answer any of your queries 24x7",
  },
  {
    icon : '/svgs/Vector10.svg',
    title : "Partnership",
    description : "Partner with us? Reach out and we'll explore all opportunities.",
  },
]
export const industryOptions = [
  { value: 'Advertising/Marketing', label: 'Advertising/Marketing' },
  { value: 'Agriculture', label: 'Agriculture' },
  { value: 'Automotive', label: 'Automotive' },
  { value: 'Business Services', label: 'Business Services' },
  { value: 'Construction', label: 'Construction' },
  { value: 'Education', label: 'Education' },
  { value: 'Energy', label: 'Energy' },
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Financial Services', label: 'Financial Services' },
  { value: 'Food & Beverage', label: 'Food & Beverage' },
  { value: 'Government', label: 'Government' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Hospitality', label: 'Hospitality' },
  { value: 'Information Technology', label: 'Information Technology' },
  { value: 'Insurance', label: 'Insurance' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Media', label: 'Media' },
  { value: 'Nonprofit', label: 'Nonprofit' },
  { value: 'Pharmaceuticals', label: 'Pharmaceuticals' },
  { value: 'Real Estate', label: 'Real Estate' },
  { value: 'Retail', label: 'Retail' },
  { value: 'Telecommunications', label: 'Telecommunications' },
  { value: 'Transportation', label: 'Transportation' },
  { value: 'Utilities', label: 'Utilities' },
  { value: 'Other', label: 'Other' },
];

export const sourceInquiry = [
  { value: 'Internet Search', label: 'Internet Search' },
  { value: 'Social Media (Facebook, Twitter, Instagram, LinkedIn, etc.)', label: 'Social Media (Facebook, Twitter, Instagram, LinkedIn, etc.)' },
  { value: 'Referral from a friend or colleague', label: 'Referral from a friend or colleague' },
  { value: 'Online Advertisement', label: 'Online Advertisement' },
  { value: 'Offline Advertisement (TV, Radio, Print)', label: 'Offline Advertisement (TV, Radio, Print)' },
  { value: 'Blog or Article', label: 'Blog or Article' },
  { value: 'Event or Conference', label: 'Event or Conference' },
  { value: 'Email Newsletter', label: 'Email Newsletter' },
  { value: 'Direct Mail', label: 'Direct Mail' },
  { value: 'Other (please specify)', label: 'Other (please specify)' },
];
